# Site settings
title: ¿Hay Acuerdo?
email: info@directoriolegislativo.org
description: Nivel de acuerdo en el Congreso de la Nación Argentina
baseurl: http://directoriolegislativo.github.io/hayacuerdo/
# url: http://localhost:4000	#Development mode
analytics: ""

# Google Spreadsheet
gsheet: "https://docs.google.com/spreadsheets/d/1WcgnjvqR__9gtfcD9Ru727vVaJX_OUdkbEUYi2rDxKg/pubhtml"

#twitter
twitter:
  username: '@desdewingu'

# Build settings
markdown: kramdown
permalink: pretty

gems:
- jekyll-compass
